spring:
  application:
    name: siscomercial-ecommerce

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/siscomercial
    username: postgres
    password: gjrv0907
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

---
siscomercial:
  ia:
    gemini-api-key: ${GEMINI_API_KEY:}
    modelo: gemini-3.5-flash-lite

    operacoes-sem-confirmacao:
      - consultarPedido
      - consultarProduto
      - consultarEstoque
      - consultarStatusNotaFiscal

    operacoes-com-confirmacao:
      - cadastrarProduto
      - cancelarPedido
      - emitirNotaFiscal
      - enviarDocumentoWhatsApp